### ISSUE TITLE
Penjelasan kata dari kamus tidak muncul

### ISSUE THREAD

**Issue by kakilimajogja** [lantip/batangan#3]
saya menggunakan browser chrome dari windows. setelah jawaban benar, penjelasan/arti kata tidak ada.

mohon ditambahkan, supaya saya bisa rurut belajar.

nuwun

**Comment by lantip** [comment]
Halo mas/mbak, 
Terimakasih untuk masukkannya. 
Mengenai penjelasan jawaban atau artinya, sudah ada di popupnya nggih, hanya memang masih dalam bahasa jawa.

Untuk penjelasan dalam bahasa Indonesia, kadang butuh panjang, sehingga tidak cukup ruang untuk ditampilkan di popup modals. Selain itu juga karena memang belum semua kata ada terjemahan dalam bahasa Indonesianya.

Untuk sementara begitu nggih :D  
<img width="365" alt="Screen Shot 2022-02-08 at 15 56 30" src="https://user-images.githubusercontent.com/3334064/152952350-996008b6-96a5-4b6c-b171-cc390a96c7b5.png">
