### ISSUE TITLE
keypad tidak terlihat di tampilan

### ISSUE THREAD

**Issue by kakilimajogja** [lantip/batangan#4]
saya menggunakan laptop oS windows di browser chrome. tidak bisa scroll ke bawah atau tampilan keypad tidak terlihat.

mohon ditambahkan untuk kenyamanan permainan.

nuwun

**Comment by lantip** [comment]
Siap, maturnuwun sanget.
Saya segera perbaiki.

**Comment by lantip** [comment]
Oh iya, mas @khayatzen mungkin tertarik untuk ngulik screen ini? hihi

**Comment by khayatzen** [comment]
Siap mas @lantip kulo rapikan screen ini. Suwun om @kakilimajogja temuannya

*Berabe golek windows

**Comment by khayatzen** [comment]
Mas @kakilimajogja bisa diinfokan Chrome yang njenengan pakai versi berapa?

Saya tadi coba di Chrome dan Opera browser di Windows OS running well je... hihiiii

**Comment by lantip** [comment]
mas @khayatzen saya tambahkan overflow-y auto di css untuk id main. 
mas @kakilimajogja mohon dicek lagi di chrome, apakah masih tidak bisa discroll. 

maturnuwun :D
