### ISSUE TITLE
penjelasan di hasil permainan bukan bahasa jawa

### ISSUE THREAD

**Issue by kakilimajogja** [lantip/batangan#5]
niki dolanan jetek-jetekan basa jawa. ananging, pas jawabe wis bener, kok sing mentungul malah basa inggris. mbok yo';o digawe sisan basa jawa.

nuwun mas/mbak.

**Comment by lantip** [comment]
Siap, maturnuwun, samangke kula ubah dhateng basa jawi sedanten.  :D
